package br.com.prcompany.beerevents.model.enums;

public enum BeerOrderEventEnum {
    VALIDATION_PASSED, VALIDATION_FAILED, VALIDATE_ORDER, ALLOCATE_ORDER,
    ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    BEER_ORDER_PICKED_UP, CANCEL_ORDER

}
